export const SOUND_COLORS = {
  'engine':        '#ff6b6b',
  'machinery':     '#ff9f43',
  'impact':        '#ffd32a',
  'saw':           '#26de81',
  'alert':         '#fd79a8',
  'music':         '#a29bfe',
  'busking':       '#c49bfe',
  'voice':         '#74b9ff',
  'dog':           '#55efc4',
}

export const SOUND_FINE = {
  'engine': ['small engine','medium engine','large engine'],
  'machinery': ['rock drill','jackhammer','hoe-ram','pile driver'],
  'impact': ['non-machinery impact'],
  'saw': ['chainsaw','rotating saw'],
  'alert': ['car horn','car alarm','siren','reverse beeper'],
  'music': ['stationary music','mobile music','ice cream truck'],
  'voice': ['talking','shouting','crowd','amplified speech'],
  'dog': ['dog barking'],
}

export const PERSONAS = [
  {
    id: 'maya',
    name: 'Maya',
    role: 'CS Undergrad · Tandon',
    borough: 'Elmhurst, Queens',
    color: '#ffd32a',
    schedule: [
      { h:0,  loc:'Home — Elmhurst',          sounds:[],                      db:35, noData:true, desc:'No sensor data for Queens overnight. The neighborhood is quiet but unmeasured.' },
      { h:1,  loc:'Home — Elmhurst',          sounds:[],                      db:35, noData:true, desc:'Still asleep. No Queens sensor coverage at this hour.' },
      { h:2,  loc:'Home — Elmhurst',          sounds:[],                      db:35, noData:true, desc:'Deep night. Data blind spot — one sensor in all of Queens.' },
      { h:3,  loc:'Home — Elmhurst',          sounds:[],                      db:35, noData:true, desc:'Nothing recorded here at 3am. Just the city breathing.' },
      { h:4,  loc:'Home — Elmhurst',          sounds:[],                      db:35, noData:true, desc:'Pre-dawn. Sensor offline for the night.' },
      { h:5,  loc:'Home — Elmhurst',          sounds:[],                      db:35, noData:true, desc:'Alarm goes off soon. Still no coverage.' },
      { h:6,  loc:'Home — Elmhurst',          sounds:['engine'],              db:52, desc:'Queens Blvd traffic picks up. Getting dressed.' },
      { h:7,  loc:'Elmhurst Ave F Station',   sounds:['engine','alert'],      db:68, desc:'Walking to the subway. Buses, cars, crosswalk beeps.' },
      { h:8,  loc:'F Train → Jay St',         sounds:['engine','voice'],      db:80, desc:'Packed F train. Metal on rails, people, phone calls.' },
      { h:9,  loc:'Tandon — Rogers Hall',     sounds:['voice'],               db:62, desc:'First lecture of the day. Settling in, professor getting started.' },
      { h:10, loc:'Tandon — CS Lab',          sounds:['voice','machinery'],   db:58, desc:'Lab session. Fans humming, someone drilling outside.' },
      { h:11, loc:'Tandon — Atrium',          sounds:['voice','engine'],      db:64, desc:'Between classes. Busy atrium, traffic audible from the street.' },
      { h:12, loc:'MetroTech Plaza',          sounds:['voice','engine'],      db:68, desc:'Lunch outside. Food trucks, people, delivery vans.' },
      { h:13, loc:'Tandon — Lecture Hall',    sounds:['voice'],               db:56, desc:'Afternoon class. Quiet except for one person eating loudly.' },
      { h:14, loc:'Tandon — Study Room',      sounds:['voice'],               db:52, desc:'Group project. Collaborative but contained.' },
      { h:15, loc:'Tandon — Courtyard',       sounds:['engine','alert','voice'],db:68, desc:'Outside break. Trucks reversing at loading dock nearby.' },
      { h:16, loc:'Tandon — Club Room',       sounds:['voice','music'],       db:60, desc:'Club meeting. Someone brought a speaker.' },
      { h:17, loc:'Jay St Station',           sounds:['engine','voice'],      db:74, desc:'Heading home. Rush hour platform, crowded.' },
      { h:18, loc:'F Train → Elmhurst',       sounds:['engine','voice'],      db:78, desc:'Packed train. Standing room only, loud.' },
      { h:19, loc:'Home — Elmhurst',          sounds:['voice','engine'],      db:65, desc:'Back in Queens. Neighborhood energy, family nearby.' },
      { h:20, loc:'Home — Elmhurst',          sounds:['voice','music'],       db:58, desc:'Dinner, studying. Roommates on TV in the other room.' },
      { h:21, loc:'Queens Blvd',              sounds:['engine','alert'],      db:65, desc:'Late food run. Queens Blvd never really quiets down.' },
      { h:22, loc:'Home — Elmhurst',          sounds:['voice','music'],       db:56, desc:'Back home. Neighbors above, music faint.' },
      { h:23, loc:'Home — Elmhurst',          sounds:['engine'],              db:48, desc:'Trying to sleep. Boulevard hum in the background.' },
    ]
  },
  {
    id: 'marcus',
    name: 'Prof. Marcus',
    role: 'Urban Studies Faculty · WSP',
    borough: 'Upper East Side',
    color: '#74b9ff',
    schedule: [
      { h:0,  loc:'Home — UES',               sounds:['engine'],              db:44, desc:'Late night on 2nd Ave. Cab, distant bus.' },
      { h:1,  loc:'Home — UES',               sounds:['engine'],              db:42, desc:'Quiet now. A truck.' },
      { h:2,  loc:'Home — UES',               sounds:[],                      db:38, desc:'Still. Rare for Manhattan.' },
      { h:3,  loc:'Home — UES',               sounds:[],                      db:36, desc:'Deepest quiet of the night.' },
      { h:4,  loc:'Home — UES',               sounds:['engine'],              db:42, desc:'Delivery trucks starting their rounds.' },
      { h:5,  loc:'Home — UES',               sounds:['engine','voice'],      db:50, desc:'Building staff, street cleaner going by.' },
      { h:6,  loc:'Home — UES',               sounds:['engine','voice'],      db:55, desc:'Morning routine. Coffee, news on low.' },
      { h:7,  loc:'6 Train — Downtown',       sounds:['engine','voice','alert'],db:82, desc:'Rush hour 6 train. Packed, screeching at the curve.' },
      { h:8,  loc:'Washington Square Park',   sounds:['voice','dog','music'], db:70, desc:'Walking through WSP to the office. Buskers tuning up, dogs everywhere.' },
      { h:9,  loc:'Silver Center — NYU',      sounds:['voice'],               db:58, desc:'Office hours. Students stopping by, phone on silent.' },
      { h:10, loc:'Silver Center — NYU',      sounds:['voice'],               db:62, desc:'Seminar prep. Colleagues in the hall.' },
      { h:11, loc:'Lecture Hall — NYU',       sounds:['voice'],               db:64, desc:'Teaching. Big room, forty students, good discussion today.' },
      { h:12, loc:'West Village — Lunch',     sounds:['voice','music','alert'],db:70, desc:'Lunch with a colleague. Outdoor seating, ambulance passes.' },
      { h:13, loc:'Silver Center — NYU',      sounds:['voice'],               db:58, desc:'More office hours. Steady stream of students.' },
      { h:14, loc:'Faculty Meeting — NYU',    sounds:['voice'],               db:55, desc:'Conference room. Lot of talking, not much resolved.' },
      { h:15, loc:'Washington Square Park',   sounds:['voice','dog','music'], db:68, desc:'Grading on a bench. Dogs, a guitarist, kids on the fountain.' },
      { h:16, loc:'Silver Center — NYU',      sounds:['voice','machinery'],   db:60, desc:'Back at desk. Construction audible from the window on 3rd.' },
      { h:17, loc:'6 Train — Uptown',         sounds:['engine','voice','alert'],db:80, desc:'Heading home. Still packed going north.' },
      { h:18, loc:'Home — UES',               sounds:['voice','engine'],      db:62, desc:'Back home. Neighbor in the hall, street noise.' },
      { h:19, loc:'Restaurant — UES',         sounds:['voice','music'],       db:68, desc:'Dinner out. Neighborhood place, good noise level.' },
      { h:20, loc:'Home — UES',               sounds:['voice'],               db:55, desc:'Reading. TV on low in another room.' },
      { h:21, loc:'Home — UES',               sounds:['engine'],              db:50, desc:'Winding down. 2nd Ave outside.' },
      { h:22, loc:'Home — UES',               sounds:['engine'],              db:46, desc:'Late night. Quiet now.' },
      { h:23, loc:'Home — UES',               sounds:['engine'],              db:42, desc:'Almost asleep.' },
    ]
  },
  {
    id: 'keisha',
    name: 'Keisha',
    role: 'Dog Walker · WSP',
    borough: 'West Village',
    color: '#55efc4',
    schedule: [
      { h:0,  loc:'Home — West Village',      sounds:['music','engine'],      db:55, desc:'Bar on Bleecker still going. Music through the wall.' },
      { h:1,  loc:'Home — West Village',      sounds:['music'],               db:52, desc:'Last call crowd outside. Music fading.' },
      { h:2,  loc:'Home — West Village',      sounds:['engine'],              db:47, desc:'Block quieting down. A cab.' },
      { h:3,  loc:'Home — West Village',      sounds:['engine'],              db:44, desc:'Almost silent. One car.' },
      { h:4,  loc:'Home — West Village',      sounds:[],                      db:40, desc:'Quiet. Even the Village sleeps eventually.' },
      { h:5,  loc:'Home — West Village',      sounds:['engine'],              db:44, desc:'First delivery trucks. Getting up soon.' },
      { h:6,  loc:'Washington Square Park',   sounds:['dog','voice'],         db:58, desc:'First walk of the day. Off-leash hour, three dogs, dewy grass.' },
      { h:7,  loc:'Washington Square Park',   sounds:['dog','music','voice'], db:65, desc:'Park filling up. Busker on guitar, dogs everywhere, runners.' },
      { h:8,  loc:'West Village Streets',     sounds:['dog','engine'],        db:62, desc:'Dropping the morning clients off. Good dogs today.' },
      { h:9,  loc:'Silver Center — NYU',      sounds:['voice'],               db:60, desc:'Morning class. Running a little late from the walks.' },
      { h:10, loc:'Silver Center — NYU',      sounds:['voice'],               db:57, desc:'Still in class. Trying to focus.' },
      { h:11, loc:'Washington Square Park',   sounds:['dog','voice','music'], db:68, desc:'Midday walks. Four dogs, two of them know each other.' },
      { h:12, loc:'Washington Square Park',   sounds:['dog','music','voice','alert'],db:73, desc:'Peak park hour. Every dog in the Village is here. A siren.' },
      { h:13, loc:'Bleecker St — Lunch',      sounds:['voice','music'],       db:66, desc:'Quick lunch. Sandwich place, music on.' },
      { h:14, loc:'Washington Square Park',   sounds:['dog','voice'],         db:63, desc:'Afternoon rounds. Calmer today, overcast.' },
      { h:15, loc:'Washington Square Park',   sounds:['dog','music','voice'], db:72, desc:'After school rush. Kids, skateboards, dogs, a trumpet.' },
      { h:16, loc:'Washington Square Park',   sounds:['dog','music','alert'], db:70, desc:'Ice cream truck rolls in. Dogs go absolutely feral.' },
      { h:17, loc:'West Village Streets',     sounds:['dog','voice','engine'],db:65, desc:'Evening walks. Last round of clients.' },
      { h:18, loc:'Home — West Village',      sounds:['voice','music'],       db:60, desc:'Home. Cooking, music on.' },
      { h:19, loc:'Home — West Village',      sounds:['voice'],               db:56, desc:'Studying for class tomorrow.' },
      { h:20, loc:'Home — West Village',      sounds:['dog','voice'],         db:58, desc:'Neighbor\'s dog barking down the hall.' },
      { h:21, loc:'Home — West Village',      sounds:['music'],               db:55, desc:'Playlist on. Reading.' },
      { h:22, loc:'Home — West Village',      sounds:['music','engine'],      db:58, desc:'Bar getting loud again. It\'s Wednesday but whatever.' },
      { h:23, loc:'Home — West Village',      sounds:['music'],               db:54, desc:'Drifting off. Still audible from downstairs.' },
    ]
  },
  {
    id: 'carlos',
    name: 'Carlos',
    role: 'Facilities Crew · Tandon',
    borough: 'Sunset Park, Bk',
    color: '#ff9f43',
    schedule: [
      { h:0,  loc:'Home — Sunset Park',       sounds:['engine'],              db:48, desc:'Traffic on 4th Ave. Quiet block otherwise.' },
      { h:1,  loc:'Home — Sunset Park',       sounds:['engine'],              db:46, desc:'Asleep. Distant highway.' },
      { h:2,  loc:'Home — Sunset Park',       sounds:[],                      db:42, desc:'Silent.' },
      { h:3,  loc:'Home — Sunset Park',       sounds:[],                      db:40, desc:'Deep sleep.' },
      { h:4,  loc:'Home — Sunset Park',       sounds:['engine'],              db:44, desc:'Early trucks on 3rd Ave.' },
      { h:5,  loc:'Home — Sunset Park',       sounds:['engine','voice'],      db:54, desc:'Up early. Street outside waking up, neighbor\'s door.' },
      { h:6,  loc:'D Train → Atlantic Ave',   sounds:['engine','voice'],      db:76, desc:'Subway in. Not too crowded yet.' },
      { h:7,  loc:'Tandon — Site Prep',       sounds:['machinery','engine'],  db:72, desc:'On site early. Setting up equipment, truck unloading.' },
      { h:8,  loc:'Tandon — Construction',    sounds:['machinery','impact'],  db:85, desc:'Work starts. Compacting, breaking ground.' },
      { h:9,  loc:'Tandon — Construction',    sounds:['machinery','impact'],  db:88, desc:'Jackhammer on the utility trench. Loud day.' },
      { h:10, loc:'Tandon — Construction',    sounds:['saw','machinery'],     db:86, desc:'Cutting steel framing. Saw whine, sparks.' },
      { h:11, loc:'Tandon — Construction',    sounds:['machinery','saw','impact'],db:84, desc:'All at once for a bit. Coordinating with another crew.' },
      { h:12, loc:'MetroTech — Lunch',        sounds:['voice','engine'],      db:65, desc:'Lunch on the plaza. Feet up, sandwich, trucks going by.' },
      { h:13, loc:'Tandon — Construction',    sounds:['machinery','saw'],     db:83, desc:'Back at it. Afternoon cutting.' },
      { h:14, loc:'Tandon — Construction',    sounds:['machinery','alert','impact'],db:80, desc:'Loading dock activity. Reverse beepers, big delivery.' },
      { h:15, loc:'Tandon — Construction',    sounds:['saw','machinery'],     db:83, desc:'Pipe cuts. Long afternoon.' },
      { h:16, loc:'Tandon — Wrap-up',         sounds:['machinery','engine'],  db:74, desc:'Cleaning up. Equipment powered down, truck reversing out.' },
      { h:17, loc:'D Train → Sunset Park',    sounds:['engine','voice'],      db:74, desc:'Heading home. Rush hour but he gets a seat.' },
      { h:18, loc:'Home — Sunset Park',       sounds:['voice','engine'],      db:60, desc:'Home. Kids outside, dinner smells.' },
      { h:19, loc:'Home — Sunset Park',       sounds:['voice','music'],       db:58, desc:'Dinner. TV on, family around.' },
      { h:20, loc:'Home — Sunset Park',       sounds:['voice'],               db:54, desc:'Winding down. Quiet evening.' },
      { h:21, loc:'Home — Sunset Park',       sounds:['engine'],              db:48, desc:'Almost out. 4th Ave traffic.' },
      { h:22, loc:'Home — Sunset Park',       sounds:['engine'],              db:46, desc:'Asleep.' },
      { h:23, loc:'Home — Sunset Park',       sounds:['engine'],              db:44, desc:'Late night. Trucks on the avenue.' },
    ]
  },
  {
    id: 'amara',
    name: 'Amara',
    role: 'Music MFA · Busker · WSP',
    borough: 'Bed-Stuy, Bk',
    color: '#a29bfe',
    schedule: [
      { h:0,  loc:'Home — Bed-Stuy',          sounds:['music','voice'],       db:65, desc:'Just got in from a gig. Neighbors still up, music through the floor.' },
      { h:1,  loc:'Home — Bed-Stuy',          sounds:['music','engine'],      db:58, desc:'Winding down. Music on low.' },
      { h:2,  loc:'Home — Bed-Stuy',          sounds:['engine'],              db:46, desc:'Asleep. L train rumbles past.' },
      { h:3,  loc:'Home — Bed-Stuy',          sounds:['engine'],              db:44, desc:'Quiet block. Occasional car.' },
      { h:4,  loc:'Home — Bed-Stuy',          sounds:[],                      db:40, desc:'Still.' },
      { h:5,  loc:'Home — Bed-Stuy',          sounds:['engine'],              db:44, desc:'First bus. Stirring.' },
      { h:6,  loc:'Home — Bed-Stuy',          sounds:['voice','engine'],      db:52, desc:'Slow morning. Neighbor in the hall.' },
      { h:7,  loc:'Home — Bed-Stuy',          sounds:['voice','engine'],      db:55, desc:'Getting ready. Music on while making coffee.' },
      { h:8,  loc:'A Train → West 4th',       sounds:['engine','voice','music'],db:78, desc:'Subway to WSP. Someone\'s playing in the car.' },
      { h:9,  loc:'NYU Music Building',       sounds:['music','voice'],       db:65, desc:'Practice room. Working on a new piece.' },
      { h:10, loc:'NYU — Composition Class',  sounds:['music','voice'],       db:62, desc:'Class. Everyone playing something different in their head.' },
      { h:11, loc:'NYU — Ensemble Rehearsal', sounds:['music','voice'],       db:68, desc:'Rehearsal. Full group today, actually sounding good.' },
      { h:12, loc:'West Village — Lunch',     sounds:['voice','music','alert'],db:70, desc:'Lunch near campus. Street noise, a car alarm briefly.' },
      { h:13, loc:'Washington Square Park',   sounds:['busking','voice'],          db:66, desc:'Setting up the busking spot. Good crowd already.' },
      { h:14, loc:'Washington Square Park',   sounds:['busking','voice','alert'],  db:73, desc:'Playing. Crowd gathering. Someone tries to talk over her.' },
      { h:15, loc:'Washington Square Park',   sounds:['busking','voice','dog'],    db:76, desc:'Peak hour. Biggest crowd of the day. Dogs keep stopping to listen.' },
      { h:16, loc:'Washington Square Park',   sounds:['busking','voice','alert'],  db:74, desc:'Still going. Kids from school, tourists, regulars.' },
      { h:17, loc:'Washington Square Park',   sounds:['busking','voice','engine','alert'],db:77, desc:'Rush hour around the park. Busiest sonic moment of the day.' },
      { h:18, loc:'A Train → Bed-Stuy',       sounds:['engine','voice'],      db:78, desc:'Heading home, gear in tow.' },
      { h:19, loc:'Home — Bed-Stuy',          sounds:['voice','music'],       db:63, desc:'Home. Neighbor practicing bass. She doesn\'t mind.' },
      { h:20, loc:'Home — Bed-Stuy',          sounds:['music','voice'],       db:70, desc:'Jam session with the neighbor. Kitchen turned studio.' },
      { h:21, loc:'Home — Bed-Stuy',          sounds:['music','voice'],       db:66, desc:'Still going. Lost track of time.' },
      { h:22, loc:'Home — Bed-Stuy',          sounds:['music'],               db:60, desc:'Winding down. Playing quietly now.' },
      { h:23, loc:'Home — Bed-Stuy',          sounds:['music','engine'],      db:55, desc:'Late. Headphones on. L train.' },
    ]
  },
  {
    id: 'lin',
    name: 'Dr. Lin',
    role: 'CUSP Researcher · Tandon',
    borough: 'Carroll Gardens, Bk',
    color: '#26de81',
    schedule: [
      { h:0,  loc:'Home — Carroll Gardens',   sounds:['engine'],              db:46, desc:'Smith St quiet. Occasional car.' },
      { h:1,  loc:'Home — Carroll Gardens',   sounds:[],                      db:40, desc:'Asleep.' },
      { h:2,  loc:'Home — Carroll Gardens',   sounds:[],                      db:38, desc:'Still.' },
      { h:3,  loc:'Home — Carroll Gardens',   sounds:[],                      db:36, desc:'Quiet neighborhood at 3am.' },
      { h:4,  loc:'Home — Carroll Gardens',   sounds:['engine'],              db:42, desc:'Early delivery on Court St.' },
      { h:5,  loc:'Home — Carroll Gardens',   sounds:['engine','voice'],      db:50, desc:'Up early. Getting ready.' },
      { h:6,  loc:'Home — Carroll Gardens',   sounds:['voice','engine'],      db:54, desc:'Coffee, checking data from overnight jobs.' },
      { h:7,  loc:'F Train → Jay St',         sounds:['engine','voice'],      db:76, desc:'Subway in. Reading on the train.' },
      { h:8,  loc:'Tandon — CUSP Lab',        sounds:['voice'],               db:58, desc:'In the lab early. Good time to think.' },
      { h:9,  loc:'Tandon — CUSP Lab',        sounds:['voice'],               db:60, desc:'Team standup. Everyone updating each other on their models.' },
      { h:10, loc:'Tandon — CUSP Lab',        sounds:['voice','engine'],      db:55, desc:'Data pipeline running. Machine hum, Carlos\'s crew audible outside.' },
      { h:11, loc:'Tandon — CUSP Lab',        sounds:['voice','machinery'],   db:60, desc:'Construction from across the building. Hard to ignore.' },
      { h:12, loc:'MetroTech — Lunch',        sounds:['voice','engine'],      db:66, desc:'Lunch outside. Sitting near the fountain.' },
      { h:13, loc:'Tandon — Seminar',         sounds:['voice'],               db:58, desc:'Guest lecture. Good one today.' },
      { h:14, loc:'Tandon — CUSP Lab',        sounds:['voice','machinery'],   db:57, desc:'Writing. Construction still going but tuning it out.' },
      { h:15, loc:'Tandon — CUSP Lab',        sounds:['voice'],               db:52, desc:'Quiet stretch. Deep work.' },
      { h:16, loc:'MetroTech — Walk',         sounds:['engine','voice','alert'],db:65, desc:'Short walk outside. Clearing the head.' },
      { h:17, loc:'F Train → Carroll Gardens',sounds:['engine','voice'],      db:74, desc:'Heading home. Easier commute going this direction.' },
      { h:18, loc:'Home — Carroll Gardens',   sounds:['voice','music'],       db:63, desc:'Back home. Neighbor\'s cooking, music.' },
      { h:19, loc:'Smith St — Dinner',        sounds:['voice','music'],       db:70, desc:'Dinner out. Lively block, restaurant full.' },
      { h:20, loc:'Home — Carroll Gardens',   sounds:['voice'],               db:58, desc:'Home, reading.' },
      { h:21, loc:'Home — Carroll Gardens',   sounds:['engine'],              db:50, desc:'Quiet evening.' },
      { h:22, loc:'Home — Carroll Gardens',   sounds:['engine'],              db:47, desc:'Late. Winding down.' },
      { h:23, loc:'Home — Carroll Gardens',   sounds:['engine'],              db:44, desc:'Asleep soon.' },
    ]
  },
  {
    id: 'jordan',
    name: 'Jordan',
    role: 'Night Security · Tandon',
    borough: 'Bushwick, Bk',
    color: '#fd79a8',
    schedule: [
      { h:0,  loc:'Tandon — Security Desk',   sounds:['engine'],              db:50, desc:'Midnight. Lobby quiet. Hum of the building systems.' },
      { h:1,  loc:'Tandon — Rounds',          sounds:['engine'],              db:46, desc:'Walking the floors. Empty hallways, lights on timers.' },
      { h:2,  loc:'Tandon — Security Desk',   sounds:['engine','alert'],      db:48, desc:'Back at the desk. A motion sensor trips, nothing there.' },
      { h:3,  loc:'Tandon — Rounds',          sounds:['engine'],              db:44, desc:'Quietest hour. Just the HVAC.' },
      { h:4,  loc:'Tandon — Loading Dock',    sounds:['machinery','engine','alert'],db:52, desc:'Early delivery crew shows up. Reverse beepers, truck.' },
      { h:5,  loc:'Tandon — Security Desk',   sounds:['engine'],              db:50, desc:'Last hour of shift. Counting down.' },
      { h:6,  loc:'L/M Train → Bushwick',     sounds:['engine','voice'],      db:72, desc:'Commute home. Subway filling up already.' },
      { h:7,  loc:'Home — Bushwick',          sounds:['engine','music'],      db:60, desc:'Arrived. Block waking up. Someone\'s playing music.' },
      { h:8,  loc:'Home — Bushwick',          sounds:['voice','engine'],      db:58, desc:'Trying to sleep. Neighbors leaving for work.' },
      { h:9,  loc:'Home — Bushwick',          sounds:['engine'],              db:50, desc:'Asleep. Street noise through the window.' },
      { h:10, loc:'Home — Bushwick',          sounds:['engine'],              db:48, desc:'Still out.' },
      { h:11, loc:'Home — Bushwick',          sounds:['engine','machinery'],  db:52, desc:'Something woke up. Construction nearby.' },
      { h:12, loc:'Home — Bushwick',          sounds:['voice','engine'],      db:58, desc:'Up for a bit. Coffee, check the phone.' },
      { h:13, loc:'Home — Bushwick',          sounds:['voice','music'],       db:58, desc:'Eating. TV on.' },
      { h:14, loc:'Bushwick Streets',         sounds:['engine','voice','music'],db:65, desc:'Running errands. Neighborhood active in the afternoon.' },
      { h:15, loc:'Home — Bushwick',          sounds:['voice','music'],       db:60, desc:'Back home. Getting ready for the night eventually.' },
      { h:16, loc:'Home — Bushwick',          sounds:['voice'],               db:55, desc:'Quiet time before the shift. Reading.' },
      { h:17, loc:'Home — Bushwick',          sounds:['voice','music'],       db:58, desc:'Dinner. Music on.' },
      { h:18, loc:'L/M Train → Tandon',       sounds:['engine','voice','alert'],db:74, desc:'Commute in. Evening subway.' },
      { h:19, loc:'Tandon — Pre-shift',       sounds:['voice','engine'],      db:62, desc:'Arrived early. Handoff from the day person.' },
      { h:20, loc:'Tandon — Security Desk',   sounds:['engine','alert'],      db:62, desc:'Shift started. Building winding down.' },
      { h:21, loc:'Tandon — Rounds',          sounds:['alert','engine'],      db:58, desc:'Evening rounds. Few people still in labs.' },
      { h:22, loc:'Tandon — Security Desk',   sounds:['engine'],              db:55, desc:'Quieting down. Last researchers leaving.' },
      { h:23, loc:'Tandon — Rounds',          sounds:['engine','alert'],      db:52, desc:'Almost empty. One more sweep.' },
    ]
  },
  {
    id: 'rosa',
    name: 'Rosa',
    role: 'Food Cart Vendor · WSP',
    borough: 'Lower East Side',
    color: '#ff6b6b',
    schedule: [
      { h:0,  loc:'Home — LES',               sounds:['music','engine'],      db:60, desc:'LES late night. Bar crowd outside, music leaking out.' },
      { h:1,  loc:'Home — LES',               sounds:['music','voice'],       db:58, desc:'Still going out there. She\'s used to it.' },
      { h:2,  loc:'Home — LES',               sounds:['engine'],              db:52, desc:'Quieter now. Ubers idling.' },
      { h:3,  loc:'Home — LES',               sounds:['engine'],              db:48, desc:'Almost silent.' },
      { h:4,  loc:'Home — LES',               sounds:['engine'],              db:46, desc:'Alarm soon. Delivery trucks starting.' },
      { h:5,  loc:'Home — LES',               sounds:['engine','voice'],      db:55, desc:'Up early. Prepping the cart, neighbor also up.' },
      { h:6,  loc:'Walking to WSP',           sounds:['engine','alert'],      db:65, desc:'Rolling the cart over. Few trucks still making deliveries.' },
      { h:7,  loc:'Washington Square — Setup', sounds:['voice','engine'],     db:67, desc:'Setting up. A couple regulars already waiting.' },
      { h:8,  loc:'Washington Square — Cart',  sounds:['voice','alert','engine'],db:72, desc:'Morning coffee rush. Students, faculty, dog walkers.' },
      { h:9,  loc:'Washington Square — Cart',  sounds:['voice','engine','alert'],db:70, desc:'Steady stream. Knows most of the morning people by now.' },
      { h:10, loc:'Washington Square — Cart',  sounds:['voice','music'],      db:67, desc:'Slowing a little. A busker started up nearby.' },
      { h:11, loc:'Washington Square — Cart',  sounds:['voice','engine'],     db:65, desc:'Pre-lunch quiet. Restocking.' },
      { h:12, loc:'Washington Square — Cart',  sounds:['voice','alert','music'],db:75, desc:'Lunch rush. Biggest crowd of the day. Everyone moving fast.' },
      { h:13, loc:'Washington Square — Cart',  sounds:['voice','music','dog'],db:70, desc:'Post-lunch. Lingerers, dogs, a group of tourists.' },
      { h:14, loc:'Washington Square — Cart',  sounds:['voice','music','dog'],db:64, desc:'Slow afternoon. Good for catching up.' },
      { h:15, loc:'Washington Square — Cart',  sounds:['voice','dog','music'],db:67, desc:'After-school crowd arrives. Energy picks up.' },
      { h:16, loc:'Washington Square — Cart',  sounds:['dog','music','alert'],db:70, desc:'Ice cream truck rolls past. Her regulars stay loyal.' },
      { h:17, loc:'Washington Square — Cart',  sounds:['voice','engine','alert'],db:73, desc:'Evening rush through the park. Commuters cutting across.' },
      { h:18, loc:'Walking home — LES',        sounds:['engine','voice'],     db:65, desc:'Packing up, heading back. Tired legs.' },
      { h:19, loc:'Home — LES',               sounds:['voice','music'],       db:60, desc:'Home. Family, food, phone calls.' },
      { h:20, loc:'Home — LES',               sounds:['voice','music'],       db:62, desc:'LES evening. Music from the restaurant downstairs.' },
      { h:21, loc:'Home — LES',               sounds:['music','engine'],      db:64, desc:'Neighborhood picking up. A few bars getting busy.' },
      { h:22, loc:'Home — LES',               sounds:['music','voice'],       db:62, desc:'It\'s a thing on this block. She\'s asleep through it mostly.' },
      { h:23, loc:'Home — LES',               sounds:['music','engine'],      db:58, desc:'Late. The city keeps going either way.' },
    ]
  },
]
