export const SOUND_COLORS = {
  'engine':    '#ff6b6b',
  'machinery': '#ff9f43',
  'impact':    '#d4a010',
  'saw':       '#26de81',
  'alert':     '#fd79a8',
  'music':     '#a29bfe',
  'voice':     '#74b9ff',
  'dog':       '#55efc4',
}

export const SOUND_FINE = {
  'engine':    ['small engine', 'medium engine', 'large engine'],
  'machinery': ['rock drill', 'jackhammer', 'hoe-ram', 'pile driver'],
  'impact':    ['non-machinery impact'],
  'saw':       ['chainsaw', 'rotating saw'],
  'alert':     ['car horn', 'car alarm', 'siren', 'reverse beeper'],
  'music':     ['stationary music', 'mobile music', 'ice cream truck'],
  'voice':     ['talking', 'shouting', 'crowd', 'amplified speech'],
  'dog':       ['dog barking'],
}

// borough: 1=Manhattan, 3=Brooklyn, 4=Queens
// sounds and db are derived at runtime from hourly-stats.json — not stored here

export const PERSONAS = [
  {
    id: 'amara',
    name: 'Amara',
    role: 'Music MFA · Busker',
    home: 'Bed-Stuy, Brooklyn',
    color: '#a29bfe',
    schedule: [
      { h:0,  lat:40.6872, lng:-73.9418, loc:'Home — Bed-Stuy',         borough:3, desc:'Asleep. Late night is quiet on this block — the music stopped around midnight.' },
      { h:1,  lat:40.6872, lng:-73.9418, loc:'Home — Bed-Stuy',         borough:3, desc:'Asleep. Engine and a distant voice. The city doesn\'t fully stop.' },
      { h:2,  lat:40.6872, lng:-73.9418, loc:'Home — Bed-Stuy',         borough:3, desc:'Asleep.' },
      { h:3,  lat:40.6872, lng:-73.9418, loc:'Home — Bed-Stuy',         borough:3, desc:'Asleep. A siren passes somewhere on Atlantic. She doesn\'t stir.' },
      { h:4,  lat:40.6872, lng:-73.9418, loc:'Home — Bed-Stuy',         borough:3, desc:'Asleep. Delivery trucks starting their rounds on the avenue.' },
      { h:5,  lat:40.6872, lng:-73.9418, loc:'Home — Bed-Stuy',         borough:3, desc:'Asleep. Alarm set for 6:30.' },
      { h:6,  lat:40.6872, lng:-73.9418, loc:'Bed-Stuy — Morning',      borough:3, desc:'Waking up. Something is already playing from the apartment above. 33% of SONYC recordings in Brooklyn this hour have music — the highest of any borough at 6am. She\'s noticed.' },
      { h:7,  lat:40.6910, lng:-73.9450, loc:'Walking to Atlantic Ave',  borough:3, desc:'Heading to the A/C. Music still audible from stoops, open windows, a guy with a speaker on his bike. Brooklyn h7: 30% music prevalence.' },
      { h:8,  lat:40.7050, lng:-73.9500, loc:'A/C Train — Manhattan',   borough:1, desc:'Crossing into Manhattan. The train surfaces briefly over the canal. The sonic texture shifts — fewer instruments, more engines and machines.' },
      { h:9,  lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Setting up at the fountain. Finds a spot near the arch. A few other musicians already here.' },
      { h:10, lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Mid-morning. The park fills. Dog walkers, students, office workers cutting through.' },
      { h:11, lat:40.7290, lng:-73.9968, loc:'NYU Steinhardt',           borough:1, desc:'Ear training. An hour inside an acoustically controlled room — a strange contrast to the morning.' },
      { h:12, lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Back at the fountain. Lunch crowd. Voice at 28% of recordings — the park is at full volume.' },
      { h:13, lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Best hour for tips. People slow down, linger, listen. Alert at 17% — an ambulance passes every few minutes.' },
      { h:14, lat:40.7290, lng:-73.9968, loc:'NYU Steinhardt',           borough:1, desc:'Afternoon studio session. Composing. Outside: voice 34%, the park audible from the practice room window.' },
      { h:15, lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'One more set before packing up. Voice 40%, music 6.5%, dogs 5.8%. The park at its loudest.' },
      { h:16, lat:40.7345, lng:-74.0058, loc:'West Village — Walking',   borough:1, desc:'Heading toward the A/C. Wandering a bit. Music 8.1% in Manhattan this hour — buskers and shop speakers.' },
      { h:17, lat:40.7200, lng:-73.9900, loc:'A/C Train — Brooklyn',     borough:3, desc:'Heading home. Rush hour. Platform packed. Voice 50%, music 27% in Brooklyn by the time she resurfaces.' },
      { h:18, lat:40.6960, lng:-73.9400, loc:'Nostrand Ave — Walking',   borough:3, desc:'Walking home from the station. Music at 32% on the block. Someone\'s playing from a second-floor window.' },
      { h:19, lat:40.6872, lng:-73.9418, loc:'Home — Bed-Stuy',         borough:3, desc:'Home. Cooks with the window open. Music 23% outside, voice 37%. The block is active.' },
      { h:20, lat:40.6872, lng:-73.9418, loc:'Bed-Stuy — Stoop',        borough:3, desc:'Sits outside with a beer. Music at 34% of Brooklyn recordings this hour — the evening peak is starting.' },
      { h:21, lat:40.6872, lng:-73.9418, loc:'Bed-Stuy — Stoop',        borough:3, desc:'42.2% music prevalence. The single highest in the entire SONYC dataset. Every window on the block is playing something different.' },
      { h:22, lat:40.6872, lng:-73.9418, loc:'Home — Bed-Stuy',         borough:3, desc:'Inside. Playing something quiet for herself. The block is still going.' },
      { h:23, lat:40.6872, lng:-73.9418, loc:'Home — Bed-Stuy',         borough:3, desc:'Alert signals spike in Brooklyn at this hour — 53%. Sirens on the avenue. She falls asleep to it.' },
    ]
  },
  {
    id: 'carlos',
    name: 'Carlos',
    role: 'Construction Crew · Tandon Site',
    home: 'Sunset Park, Brooklyn',
    color: '#ff9f43',
    schedule: [
      { h:0,  lat:40.6462, lng:-74.0097, loc:'Home — Sunset Park',       borough:3, desc:'Asleep. BQE hum through the window. Engine on 4th Ave. Unremarkable.' },
      { h:1,  lat:40.6462, lng:-74.0097, loc:'Home — Sunset Park',       borough:3, desc:'Asleep.' },
      { h:2,  lat:40.6462, lng:-74.0097, loc:'Home — Sunset Park',       borough:3, desc:'Asleep.' },
      { h:3,  lat:40.6462, lng:-74.0097, loc:'Home — Sunset Park',       borough:3, desc:'Alarm at 3:45. He doesn\'t really wake till 4.' },
      { h:4,  lat:40.6462, lng:-74.0097, loc:'Home — Sunset Park',       borough:3, desc:'Up. Coffee, gear, lunch packed. Out by 4:30. The street is just delivery trucks.' },
      { h:5,  lat:40.6550, lng:-74.0050, loc:'D Train Platform',         borough:3, desc:'Walking to the D. Brooklyn 5am: voice 21%, mostly workers like him. Music 8% — already.' },
      { h:6,  lat:40.6872, lng:-73.9600, loc:'D Train — Manhattan',      borough:3, desc:'Riding through Brooklyn. Music 33% this hour — he hears it through the platform doors. Six years on this commute and it still feels early.' },
      { h:7,  lat:40.7300, lng:-73.9980, loc:'Manhattan Job Site',       borough:1, desc:'Crew on site. The saw fires up at 7:01. Powered saw at 18.5% in Manhattan recordings this hour — the highest in the dataset. Machinery at 10.8%. The neighborhood wakes to this.' },
      { h:8,  lat:40.7300, lng:-73.9980, loc:'Manhattan Job Site',       borough:1, desc:'Full swing. Machinery 15.6%, saw 10.6%, 84 dB average. Jackhammer, rock drill, rotating saw. A noise complaint was probably filed at 7:30.' },
      { h:9,  lat:40.7300, lng:-73.9980, loc:'Manhattan Job Site',       borough:1, desc:'Still going. 17.4% machinery — peak of the peak. Loudest stretch of his day.' },
      { h:10, lat:40.7300, lng:-73.9980, loc:'Manhattan Job Site',       borough:1, desc:'Midmorning grind. 16.5% machinery. Voice growing outside the fence — the neighborhood is awake and not happy.' },
      { h:11, lat:40.7300, lng:-73.9980, loc:'Manhattan Job Site',       borough:1, desc:'Machinery tapering. Lunch coming. The site gets quieter as the morning crew rotates.' },
      { h:12, lat:40.7300, lng:-73.9990, loc:'Manhattan — Deli nearby',  borough:1, desc:'Lunch break. Around the corner. Voice 28% on the street — a completely different world from inside the fence.' },
      { h:13, lat:40.7300, lng:-73.9980, loc:'Manhattan Job Site',       borough:1, desc:'Afternoon session. Lighter work — laying conduit, less noise.' },
      { h:14, lat:40.7300, lng:-73.9980, loc:'Manhattan Job Site',       borough:1, desc:'Voice 34.2% of recordings on this block now. The city has shifted to afternoon.' },
      { h:15, lat:40.7300, lng:-73.9980, loc:'Manhattan Job Site',       borough:1, desc:'Packing tools. Voice 40%, alert 19.7%. Just another afternoon.' },
      { h:16, lat:40.7300, lng:-73.9980, loc:'Manhattan — Street',       borough:1, desc:'Done. Street level. Voice 41%, alert 19.9%, engine 28.7%. Rush hour Manhattan.' },
      { h:17, lat:40.7200, lng:-73.9900, loc:'D Train — Brooklyn',       borough:3, desc:'Packed train home. Voice 50%, music 27% in Brooklyn. He can hear it when the doors open.' },
      { h:18, lat:40.6600, lng:-74.0050, loc:'Home — Sunset Park',       borough:3, desc:'Back in Sunset Park. Music 32% in Brooklyn this hour. Kids on the block, neighbors out front.' },
      { h:19, lat:40.6462, lng:-74.0097, loc:'Home — Sunset Park',       borough:3, desc:'Dinner. TV on. Music 23%, voice 38% outside. Neighbors talking on the stoop.' },
      { h:20, lat:40.6462, lng:-74.0097, loc:'Home — Sunset Park',       borough:3, desc:'Outside for a bit. Music 34% in Brooklyn — the evening peak starting. He\'s got a 3:45 alarm.' },
      { h:21, lat:40.6462, lng:-74.0097, loc:'Home — Sunset Park',       borough:3, desc:'Asleep. Music at 42% outside — the highest music hour in the dataset. He sleeps through all of it.' },
      { h:22, lat:40.6462, lng:-74.0097, loc:'Home — Sunset Park',       borough:3, desc:'Asleep.' },
      { h:23, lat:40.6462, lng:-74.0097, loc:'Home — Sunset Park',       borough:3, desc:'Asleep. Alert spikes at 53% in Brooklyn late night. A siren. He doesn\'t wake.' },
    ]
  },
  {
    id: 'maya',
    name: 'Maya',
    role: 'CS Undergrad · Tandon',
    home: 'Elmhurst, Queens',
    color: '#d4a010',
    schedule: [
      { h:0,  lat:40.7372, lng:-73.8800, loc:'Home — Elmhurst',          borough:4, desc:'Asleep. No SONYC sensor coverage in Elmhurst overnight. The city here is unmeasured.' },
      { h:1,  lat:40.7372, lng:-73.8800, loc:'Home — Elmhurst',          borough:4, desc:'Asleep. The dataset has nothing to say about this corner of Queens at 1am.' },
      { h:2,  lat:40.7372, lng:-73.8800, loc:'Home — Elmhurst',          borough:4, desc:'Asleep. Data void. One sensor in all of Queens, and it goes dark at night.' },
      { h:3,  lat:40.7372, lng:-73.8800, loc:'Home — Elmhurst',          borough:4, desc:'Asleep. The silence in the dataset isn\'t the absence of sound — it\'s the absence of measurement.' },
      { h:4,  lat:40.7372, lng:-73.8800, loc:'Home — Elmhurst',          borough:4, desc:'Asleep. Alarm at 6.' },
      { h:5,  lat:40.7372, lng:-73.8800, loc:'Home — Elmhurst',          borough:4, desc:'Asleep. Still no Queens data. The SONYC sensor resumes at 6am.' },
      { h:6,  lat:40.7372, lng:-73.8800, loc:'Elmhurst — Getting ready', borough:4, desc:'Alarm goes off. Queens Blvd audible from the window. Engine nearly 100% of what the sensor picks up here — trucks, buses, the boulevard never stops.' },
      { h:7,  lat:40.7372, lng:-73.8870, loc:'Elmhurst Ave F Station',   borough:4, desc:'Walking to the subway. Engine 67%, machinery 33%, alert 33% at this Queens pocket. Loud corner to start a morning.' },
      { h:8,  lat:40.7050, lng:-73.9500, loc:'F Train to Jay St',        borough:4, desc:'On the train. Entering Brooklyn data territory. The subway is its own unmeasured world.' },
      { h:9,  lat:40.6932, lng:-73.9861, loc:'Tandon — Rogers Hall',     borough:3, desc:'First lecture. Brooklyn data takes over. Morning construction audible from the courtyard.' },
      { h:10, lat:40.6932, lng:-73.9861, loc:'Tandon — CS Lab',          borough:3, desc:'Lab session. Brooklyn 10am: music 20% outside — higher than any Manhattan hour at this time.' },
      { h:11, lat:40.6924, lng:-73.9873, loc:'MetroTech Plaza',           borough:3, desc:'Between classes. Eats outside. Voice 34%, music 20%. Brooklyn midmorning.' },
      { h:12, lat:40.6924, lng:-73.9873, loc:'MetroTech Plaza',           borough:3, desc:'Lunch outside. Brooklyn noon: voice 47%, music 17%.' },
      { h:13, lat:40.6932, lng:-73.9861, loc:'Tandon — Study Room',      borough:3, desc:'Afternoon grinding through a problem set. Voice 49% outside — the neighborhood is loud.' },
      { h:14, lat:40.6932, lng:-73.9861, loc:'Tandon — Lecture Hall',    borough:3, desc:'Last class. Afternoon construction still going. Brooklyn voice 46%, machinery tapering.' },
      { h:15, lat:40.6932, lng:-73.9861, loc:'Tandon — Courtyard',       borough:3, desc:'Quick break outside. Music 14% on the street. Voice 52.5% — loudest Brooklyn hour of the day.' },
      { h:16, lat:40.6932, lng:-73.9861, loc:'Tandon — Club Room',       borough:3, desc:'Club meeting. Someone brought a speaker. Brooklyn music 18% outside.' },
      { h:17, lat:40.6920, lng:-73.9870, loc:'Jay St Station',           borough:3, desc:'Heading home. Brooklyn rush: voice 50%, music 27%. Platform crowded.' },
      { h:18, lat:40.7372, lng:-73.8800, loc:'F Train — Queens',         borough:4, desc:'Surfacing back into Queens. Switches back to Queens data. Engine at 100% of what little the sensor picks up.' },
      { h:19, lat:40.7372, lng:-73.8800, loc:'Home — Elmhurst',          borough:4, desc:'Walking home from the station. Alert at 67% in Queens this hour — the highest in the dataset. Queens Blvd is relentless: sirens, horns, alarms.' },
      { h:20, lat:40.7372, lng:-73.8800, loc:'Home — Elmhurst',          borough:4, desc:'Doing homework. Alert still 60%, engine 59% on the boulevard outside. Hard to tune out.' },
      { h:21, lat:40.7372, lng:-73.8800, loc:'Home — Elmhurst',          borough:4, desc:'Still studying. Queens sensor data goes sparse after this hour.' },
      { h:22, lat:40.7372, lng:-73.8800, loc:'Home — Elmhurst',          borough:4, desc:'Winding down. Engine 67% — the last clear reading of the night from the Queens sensor.' },
      { h:23, lat:40.7372, lng:-73.8800, loc:'Home — Elmhurst',          borough:4, desc:'Asleep. No more Queens data until morning. The measurement gap closes around her.' },
    ]
  },
  {
    id: 'keisha',
    name: 'Keisha',
    role: 'Dog Walker · Part-Time Student',
    home: 'West Village, Manhattan',
    color: '#55efc4',
    schedule: [
      { h:0,  lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Asleep. 7th Ave engine through the window. Manhattan never fully quiets.' },
      { h:1,  lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Asleep.' },
      { h:2,  lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Asleep.' },
      { h:3,  lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Asleep. Even at 3am Manhattan is 80 dB average. Delivery trucks, a taxi. She grew up here, sleeps through it.' },
      { h:4,  lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Asleep. Alarm at 5:30.' },
      { h:5,  lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Up. First walk is early — clients want 6am. She grabs three dogs from a building on Bank St.' },
      { h:6,  lat:40.7308, lng:-74.0002, loc:'Hudson River Park',        borough:1, desc:'Morning walk. Engine 40%, voice 6.5%. The park is quiet at this hour. Dogs love it.' },
      { h:7,  lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'WSP morning rounds. Dog prevalence 4.7% in Manhattan recordings this hour. She\'s one of a dozen walkers converging on the same fountain.' },
      { h:8,  lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Peak dog hour. 7.6% of Manhattan recordings have audible dogs at 8am — the highest all day. Machinery 15.6%, saw 10.6% from the site on the east side. The dogs don\'t care.' },
      { h:9,  lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Drop-offs and pickups. Dog prevalence 6%. Voice building — 10.7%, the park waking up.' },
      { h:10, lat:40.7290, lng:-73.9968, loc:'NYU — Lecture',            borough:1, desc:'Class. Sociology of urban space — relevant. Machinery 16.5% audible through the window from the construction site that\'s been going since July.' },
      { h:11, lat:40.7290, lng:-73.9968, loc:'NYU — Study Hall',         borough:1, desc:'Reading between lectures. Voice 21.5% outside on the street.' },
      { h:12, lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Midday walk. Voice 28% of recordings — the park is at lunch volume. Hard to think.' },
      { h:13, lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Another round. Alert 17.4%, engine 30.9%. An ambulance cuts through every fifteen minutes.' },
      { h:14, lat:40.7345, lng:-74.0058, loc:'West Village — Afternoon', borough:1, desc:'Afternoon circuit. Dogs 5.2%. Voice 34.2%. School isn\'t out yet but the energy is shifting.' },
      { h:15, lat:40.7345, lng:-74.0058, loc:'West Village — Walk',      borough:1, desc:'School lets out. Voice 40%, alert 19.7%. The neighborhood gets immediately louder. Kids on scooters, parents on phones.' },
      { h:16, lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Last big round. Voice 41%, music 8.1%. The park hits its most social hour. Skaters, a guy with a portable piano, the chess tables full.' },
      { h:17, lat:40.7345, lng:-74.0058, loc:'West Village — Evening',   borough:1, desc:'Drop-offs. Rush hour: voice 43.5%, alert 20.5%. The city shifts into evening gear.' },
      { h:18, lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Back home. Feeds her own dog. Voice 44.2%, alert 21.1% on the street — she can hear it with the window cracked.' },
      { h:19, lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Quick evening walk. Just hers. Voice 46.2%.' },
      { h:20, lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Home for the night. TV, half-reading. Music 7.8%, voice 45.7% outside.' },
      { h:21, lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Voice at 51.1% citywide — the peak in the entire dataset. She\'s asleep before it peaks.' },
      { h:22, lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Asleep. Voice still 44.8% outside. 5:30 alarm.' },
      { h:23, lat:40.7345, lng:-74.0058, loc:'Home — West Village',      borough:1, desc:'Asleep.' },
    ]
  },
  {
    id: 'marcus',
    name: 'Prof. Marcus',
    role: 'Urban Studies Faculty · NYU',
    home: 'Upper East Side',
    color: '#74b9ff',
    schedule: [
      { h:0,  lat:40.7800, lng:-73.9490, loc:'Home — Upper East Side',   borough:1, desc:'Asleep. 2nd Ave engine and alert. Manhattan at midnight: 79.5 dB average. He\'s lived here 22 years.' },
      { h:1,  lat:40.7800, lng:-73.9490, loc:'Home — Upper East Side',   borough:1, desc:'Asleep.' },
      { h:2,  lat:40.7800, lng:-73.9490, loc:'Home — Upper East Side',   borough:1, desc:'Asleep.' },
      { h:3,  lat:40.7800, lng:-73.9490, loc:'Home — Upper East Side',   borough:1, desc:'Asleep. Delivery trucks. Engine at 41% — the overnight economy.' },
      { h:4,  lat:40.7800, lng:-73.9490, loc:'Home — Upper East Side',   borough:1, desc:'Asleep.' },
      { h:5,  lat:40.7800, lng:-73.9490, loc:'Home — Upper East Side',   borough:1, desc:'Asleep. Alarm at 6:45.' },
      { h:6,  lat:40.7800, lng:-73.9490, loc:'Upper East Side — Morning', borough:1, desc:'Up. Coffee and the news. Morning walk before the subway. Engine 40%, voice 6.5% — the city warming up.' },
      { h:7,  lat:40.7735, lng:-73.9566, loc:'6 Train — Downtown',       borough:1, desc:'Rush hour 6 train. Packed. Above ground: powered saw at 18.5% this hour — construction has already started. 84.7 dB average. He notes it for class.' },
      { h:8,  lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Walking through WSP to Silver Center. Dogs 7.6%, machinery 15.6%, the usual morning. He\'s been tracking this commute sound for three years.' },
      { h:9,  lat:40.7290, lng:-73.9968, loc:'Silver Center — NYU',      borough:1, desc:'Office hours. Students in and out. The hallway has its own acoustic character.' },
      { h:10, lat:40.7290, lng:-73.9968, loc:'Silver Center — NYU',      borough:1, desc:'Seminar prep. Machinery 16.5% across the street — the same site that started at 7.' },
      { h:11, lat:40.7290, lng:-73.9968, loc:'Lecture Hall — NYU',       borough:1, desc:'Teaching. 40 students, good discussion today. Outside: voice 21.5%, the park getting busy.' },
      { h:12, lat:40.7308, lng:-74.0002, loc:'West Village — Lunch',     borough:1, desc:'Lunch outside with a colleague. Voice 28%, alert 16%. They have to raise their voices over an ambulance.' },
      { h:13, lat:40.7290, lng:-73.9968, loc:'Silver Center — NYU',      borough:1, desc:'Office hours. Alert 17.4%, engine 30.9% audible through the window — the afternoon street.' },
      { h:14, lat:40.7290, lng:-73.9968, loc:'Faculty Meeting — NYU',    borough:1, desc:'Conference room. Voice 34.2% outside. Inside: one person talks, everyone else checks their phone.' },
      { h:15, lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Grading on a bench. Voice 40%, music 6.5%, dogs 5.8%. The park at its loudest. He gets half a chapter done.' },
      { h:16, lat:40.7308, lng:-74.0002, loc:'Washington Square Park',   borough:1, desc:'Still outside. Voice 41.2%. The most socially active hour in the data. He watches and takes notes — literally.' },
      { h:17, lat:40.7735, lng:-73.9566, loc:'6 Train — Uptown',         borough:1, desc:'Rush hour back. Voice 43.5%, alert 20.5%. Platform too loud to grade.' },
      { h:18, lat:40.7800, lng:-73.9490, loc:'Home — Upper East Side',   borough:1, desc:'Home. Voice 44.2%, alert 21.1% on 2nd Ave — filters through even with the windows closed.' },
      { h:19, lat:40.7800, lng:-73.9490, loc:'Upper East Side — Dinner', borough:1, desc:'Neighborhood restaurant. Voice 46.2% outside. The city at its most conversational.' },
      { h:20, lat:40.7800, lng:-73.9490, loc:'Home — Upper East Side',   borough:1, desc:'Grading. Voice 45.7% on the avenue. He\'s used to it.' },
      { h:21, lat:40.7800, lng:-73.9490, loc:'Home — Upper East Side',   borough:1, desc:'Reading. Voice peaks at 51.1% citywide this hour — the loudest the data gets. He closes the window.' },
      { h:22, lat:40.7800, lng:-73.9490, loc:'Home — Upper East Side',   borough:1, desc:'Asleep. Voice still 44.8% outside. He\'s lived in Manhattan long enough that this is silence.' },
      { h:23, lat:40.7800, lng:-73.9490, loc:'Home — Upper East Side',   borough:1, desc:'Asleep.' },
    ]
  },
  {
    id: 'jordan',
    name: 'Jordan',
    role: 'Night Security · Tandon',
    home: 'Bushwick, Brooklyn',
    color: '#fd79a8',
    schedule: [
      { h:0,  lat:40.6932, lng:-73.9861, loc:'Tandon — On Shift',        borough:3, desc:'On the security desk. Building quiet inside. Brooklyn midnight: engine, occasional voice. Checks the monitors.' },
      { h:1,  lat:40.6932, lng:-73.9861, loc:'Tandon — Patrol',          borough:3, desc:'Patrol round. Walks the floors. Brooklyn 1am is as close to quiet as it gets.' },
      { h:2,  lat:40.6932, lng:-73.9861, loc:'Tandon — Security Desk',   borough:3, desc:'Long stretch. Data is thin in Brooklyn at 2am. So is conversation.' },
      { h:3,  lat:40.6932, lng:-73.9861, loc:'Tandon — Patrol',          borough:3, desc:'Slowest hour. Half a cold coffee. Engine on Jay St. Nothing else.' },
      { h:4,  lat:40.6932, lng:-73.9861, loc:'Tandon — Security Desk',   borough:3, desc:'Pre-dawn. Quiet enough that he can hear trucks on the BQE from the fourth floor.' },
      { h:5,  lat:40.6932, lng:-73.9861, loc:'Tandon — Patrol',          borough:3, desc:'Almost done. Brooklyn voice edges up to 21% — first workers, delivery guys, early students.' },
      { h:6,  lat:40.6932, lng:-73.9861, loc:'Tandon — Handoff',         borough:3, desc:'Shift ends. Steps outside. Music at 33% in Brooklyn — it happens every morning and still catches him off guard.' },
      { h:7,  lat:40.6944, lng:-73.9213, loc:'L Train — Bushwick',       borough:3, desc:'Heading home through Brooklyn. Music 30% this hour — he hears it when the subway doors open at each stop.' },
      { h:8,  lat:40.6944, lng:-73.9213, loc:'Home — Bushwick',          borough:3, desc:'Home. Blackout curtains. Music 19% outside. The neighborhood is waking up; he\'s going the other direction.' },
      { h:9,  lat:40.6944, lng:-73.9213, loc:'Home — Bushwick',          borough:3, desc:'Asleep.' },
      { h:10, lat:40.6944, lng:-73.9213, loc:'Home — Bushwick',          borough:3, desc:'Asleep. Brooklyn music at 20% outside — highest of any borough at 10am. He sleeps through all of it.' },
      { h:11, lat:40.6944, lng:-73.9213, loc:'Home — Bushwick',          borough:3, desc:'Asleep. Voice 34% building outside.' },
      { h:12, lat:40.6944, lng:-73.9213, loc:'Home — Bushwick',          borough:3, desc:'Asleep.' },
      { h:13, lat:40.6944, lng:-73.9213, loc:'Home — Bushwick',          borough:3, desc:'Waking up. Voice 49%, music 26%. The block at full afternoon volume. He lies there for a while.' },
      { h:14, lat:40.6944, lng:-73.9213, loc:'Bushwick — Errands',       borough:3, desc:'Up. Food run. Music 19%, alert 24%. Bushwick afternoon.' },
      { h:15, lat:40.6944, lng:-73.9213, loc:'Bushwick — Block',         borough:3, desc:'Outside for a bit. Voice 52.5% — the loudest Brooklyn hour of the day.' },
      { h:16, lat:40.6944, lng:-73.9213, loc:'Home — Bushwick',          borough:3, desc:'Getting ready. Pre-shift. Music 18% outside the window.' },
      { h:17, lat:40.6944, lng:-73.9213, loc:'L Train — Tandon',         borough:3, desc:'Heading in. Voice 50%, music 27% in Brooklyn. Hears it through the platform.' },
      { h:18, lat:40.6932, lng:-73.9861, loc:'Tandon — Arriving',        borough:3, desc:'Shift starts. Outside: music 32%, voice 41%. He walks in as the building empties out.' },
      { h:19, lat:40.6932, lng:-73.9861, loc:'Tandon — On Shift',        borough:3, desc:'Desk. Getting into the rhythm. Brooklyn music 23%, voice 37% — he can hear it faintly through the lobby doors.' },
      { h:20, lat:40.6932, lng:-73.9861, loc:'Tandon — Patrol',          borough:3, desc:'Patrol round. Music at 34% in Brooklyn. Through the windows of the upper floors he can see the block below, people out, speakers going.' },
      { h:21, lat:40.6932, lng:-73.9861, loc:'Tandon — Security Desk',   borough:3, desc:'42.2% music in Brooklyn — the single highest hour in the entire dataset. Inside: silence. Outside: everything.' },
      { h:22, lat:40.6932, lng:-73.9861, loc:'Tandon — Patrol',          borough:3, desc:'Late night settles. Music drops off. Engine picks back up.' },
      { h:23, lat:40.6932, lng:-73.9861, loc:'Tandon — Security Desk',   borough:3, desc:'Alert spikes to 53% in Brooklyn at this hour — sirens, car alarms. He logs it. Every night around this time.' },
    ]
  },
  {
    id: 'rosa',
    name: 'Rosa',
    role: 'Food Cart Vendor · WSP',
    home: 'Lower East Side',
    color: '#ff6b6b',
    schedule: [
      { h:0,  lat:40.7157, lng:-73.9863, loc:'Home — Lower East Side',   borough:1, desc:'Asleep. Delancey engine and alert. She\'s used to it.' },
      { h:1,  lat:40.7157, lng:-73.9863, loc:'Home — Lower East Side',   borough:1, desc:'Asleep. Voice at 23% — LES still has people out.' },
      { h:2,  lat:40.7157, lng:-73.9863, loc:'Home — Lower East Side',   borough:1, desc:'Asleep.' },
      { h:3,  lat:40.7157, lng:-73.9863, loc:'Home — Lower East Side',   borough:1, desc:'Alarm at 3:30. Lies there a minute. Gets up.' },
      { h:4,  lat:40.7157, lng:-73.9863, loc:'LES — Loading Cart',       borough:1, desc:'Prepping the cart. Loading from storage. Engine on Delancey — delivery trucks. Voice 7% — other workers.' },
      { h:5,  lat:40.7200, lng:-73.9990, loc:'Walking Cart to WSP',      borough:1, desc:'Rolling the cart uptown. 5am Manhattan: voice 3%, just workers. Engine on every block.' },
      { h:6,  lat:40.7300, lng:-74.0000, loc:'WSP Area — Setting Up',    borough:1, desc:'Setting up the cart. Engine 40%, voice 6.5%. First regulars arrive at 6:30 — construction crew from the site across the park.' },
      { h:7,  lat:40.7308, lng:-74.0002, loc:'WSP Area — Open',          borough:1, desc:'Open. Saw at 18.5% in Manhattan this hour — the highest in the dataset. The construction site is the loudest thing on the block. Her first customers work there.' },
      { h:8,  lat:40.7308, lng:-74.0002, loc:'WSP Area — Morning Rush',  borough:1, desc:'Morning rush. Dogs 7.6%, machinery 15.6%, voice growing. Students, dog walkers, office workers. The cart runs out of coffee by 9.' },
      { h:9,  lat:40.7308, lng:-74.0002, loc:'WSP Area — Steady',        borough:1, desc:'Steady stream. Alert 13.4%, engine 33.1%. The park filling in.' },
      { h:10, lat:40.7308, lng:-74.0002, loc:'WSP Area — Midmorning',    borough:1, desc:'Midmorning lull. Refills the cart. Machinery 16.5% from across the park — the drill that doesn\'t stop.' },
      { h:11, lat:40.7308, lng:-74.0002, loc:'WSP Area — Building',      borough:1, desc:'Pre-lunch building. Voice 21.5%, people emerging from offices.' },
      { h:12, lat:40.7308, lng:-74.0002, loc:'WSP Area — Lunch Peak',    borough:1, desc:'Peak hour. Voice 28%, alert 16%, engine 29%. Line around the corner. She doesn\'t stop moving for ninety minutes.' },
      { h:13, lat:40.7308, lng:-74.0002, loc:'WSP Area — Lunch',         borough:1, desc:'Still packed. Voice 27.5%. People linger, eat standing up, shout across to each other.' },
      { h:14, lat:40.7308, lng:-74.0002, loc:'WSP Area — Afternoon',     borough:1, desc:'Afternoon steady. Voice 34.2%, alert 19.6%. The crowd has a different character — tourists, students, afternoon regulars.' },
      { h:15, lat:40.7308, lng:-74.0002, loc:'WSP Area — Best Hour',     borough:1, desc:'Her favorite hour. Voice 40%, alert 19.7%, music 6.5%, dog 5.8%. The park at maximum energy. Good tips.' },
      { h:16, lat:40.7308, lng:-74.0002, loc:'WSP Area — After School',  borough:1, desc:'After school hits. Voice 41.2%, music 8.1%, dog 6.2%. Kids, skaters, a piano player at the fountain. The cart does brisk business.' },
      { h:17, lat:40.7308, lng:-74.0002, loc:'WSP Area — Rush Hour',     borough:1, desc:'Rush hour. Voice 43.5%, alert 20.5%. Everyone moving at once.' },
      { h:18, lat:40.7308, lng:-74.0002, loc:'WSP Area — Dinner Crowd',  borough:1, desc:'Dinner crowd. Voice 44.2%, music 7.9%. She starts thinking about packing up.' },
      { h:19, lat:40.7308, lng:-74.0002, loc:'WSP Area — Closing',       borough:1, desc:'Breaking down the cart. Voice 46.2%, alert 21.7%. The park keeps going without her.' },
      { h:20, lat:40.7200, lng:-73.9990, loc:'Rolling Cart Home',        borough:1, desc:'Rolling back to storage. Voice 45.7%, music 7.8%. Someone is playing guitar on the corner of Bleecker.' },
      { h:21, lat:40.7157, lng:-73.9863, loc:'Home — Lower East Side',   borough:1, desc:'Walking home. Voice 51.1% citywide — the peak in the entire dataset. The city at its most social and she\'s done for the day.' },
      { h:22, lat:40.7157, lng:-73.9863, loc:'Home — Lower East Side',   borough:1, desc:'Asleep. Ate something standing over the sink. Alarm at 3:30.' },
      { h:23, lat:40.7157, lng:-73.9863, loc:'Home — Lower East Side',   borough:1, desc:'Asleep.' },
    ]
  },
  {
    id: 'lin',
    name: 'Dr. Lin',
    role: 'CUSP Researcher · Tandon',
    home: 'Carroll Gardens, Brooklyn',
    color: '#26de81',
    schedule: [
      { h:0,  lat:40.6796, lng:-73.9989, loc:'Home — Carroll Gardens',   borough:3, desc:'Asleep. Carroll Gardens is quiet after midnight — engine on Smith St, occasional voice.' },
      { h:1,  lat:40.6796, lng:-73.9989, loc:'Home — Carroll Gardens',   borough:3, desc:'Asleep.' },
      { h:2,  lat:40.6796, lng:-73.9989, loc:'Home — Carroll Gardens',   borough:3, desc:'Asleep.' },
      { h:3,  lat:40.6796, lng:-73.9989, loc:'Home — Carroll Gardens',   borough:3, desc:'Asleep. Brooklyn data thins out before dawn — fewer recordings, fewer sensors active.' },
      { h:4,  lat:40.6796, lng:-73.9989, loc:'Home — Carroll Gardens',   borough:3, desc:'Asleep.' },
      { h:5,  lat:40.6796, lng:-73.9989, loc:'Home — Carroll Gardens',   borough:3, desc:'Alarm at 6. She reads annotation logs while the coffee brews.' },
      { h:6,  lat:40.6796, lng:-73.9989, loc:'Carroll Gardens — Walk',   borough:3, desc:'Walking to the F. Music at 33% in Brooklyn this hour — she\'s identified this pattern in the data and now she hears it everywhere. Every morning confirms it.' },
      { h:7,  lat:40.6796, lng:-73.9989, loc:'F Train — Tandon',         borough:3, desc:'Commuting. Brooklyn music 30% this hour. She counts the open windows, the parked cars with speakers, the one guy on a bike with a bluetooth speaker every block.' },
      { h:8,  lat:40.6932, lng:-73.9861, loc:'Tandon — Arriving',        borough:3, desc:'At the building. Music 19.3%, machinery 14.8% outside. She\'s studying the sounds she hears walking in.' },
      { h:9,  lat:40.6932, lng:-73.9861, loc:'Tandon — Research Lab',    borough:3, desc:'Analyzing SONYC annotations. Outside: machinery 10.7%, music 18.5%. Her window faces the street.' },
      { h:10, lat:40.6932, lng:-73.9861, loc:'Tandon — Research Lab',    borough:3, desc:'Running analysis. Brooklyn has the highest music prevalence of any borough at 10am: 20.3%. She\'s building a paper around this.' },
      { h:11, lat:40.6924, lng:-73.9873, loc:'MetroTech — Seminar',      borough:3, desc:'Lab seminar. Presenting the Brooklyn morning music anomaly. "It starts before 6am. We don\'t fully know why." Voice 34.1% outside.' },
      { h:12, lat:40.6924, lng:-73.9873, loc:'MetroTech Plaza',          borough:3, desc:'Lunch outside. Voice 46.7%, music 17.3%. She eats and takes field notes.' },
      { h:13, lat:40.6932, lng:-73.9861, loc:'Tandon — Research Lab',    borough:3, desc:'Afternoon analysis. Mapping the music anomaly across sensors. Voice 48.7%, music 25.6% outside her window.' },
      { h:14, lat:40.6932, lng:-73.9861, loc:'Tandon — Research Lab',    borough:3, desc:'Writing. Alert 24.3% — ambulances on Jay St every few minutes. She puts on headphones.' },
      { h:15, lat:40.6932, lng:-73.9861, loc:'Tandon — Writing',         borough:3, desc:'Most productive stretch. Voice 52.5% outside — loudest Brooklyn hour of the day. Doesn\'t notice.' },
      { h:16, lat:40.6932, lng:-73.9861, loc:'Tandon — Lab Check-in',    borough:3, desc:'Team check-in. Music 18.2% outside, voice 48.1%.' },
      { h:17, lat:40.6932, lng:-73.9861, loc:'F Train — Carroll Gardens', borough:3, desc:'Heading home. Voice 50.4%, music 26.8% in Brooklyn. The evening commute is its own dataset.' },
      { h:18, lat:40.6796, lng:-73.9989, loc:'Home — Carroll Gardens',   borough:3, desc:'Walking home from the station. Music at 32% on the block — she notes the timestamp.' },
      { h:19, lat:40.6796, lng:-73.9989, loc:'Carroll Gardens — Evening', borough:3, desc:'Evening walk. Music 22.6%, voice 37.5%.' },
      { h:20, lat:40.6796, lng:-73.9989, loc:'Home — Carroll Gardens',   borough:3, desc:'Home. Music 34.2% outside — Brooklyn\'s peak window starting. She has her own audio playing and barely distinguishes it from what\'s coming through the window.' },
      { h:21, lat:40.6796, lng:-73.9989, loc:'Home — Carroll Gardens',   borough:3, desc:'42.2% music in Brooklyn. She\'s been analyzing this pattern all day. Now she just sits with it.' },
      { h:22, lat:40.6796, lng:-73.9989, loc:'Home — Carroll Gardens',   borough:3, desc:'Reading. Late. Music drops to 8.3%, engine back up. Brooklyn settling.' },
      { h:23, lat:40.6796, lng:-73.9989, loc:'Home — Carroll Gardens',   borough:3, desc:'Asleep. Alert 53.3% in Brooklyn late night — the sensors catch the spike. She\'ll see it in tomorrow\'s data.' },
    ]
  },
]
